[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  publish = "dist"
  
[context.deploy-preview]
  publish = "dist"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[functions]
  directory = "netlify/functions"